[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
OMEinsumContractionOrders = "6f22d1fd-8eed-4bb7-9776-e7d684900715"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
